"""Runnable reproducibility tests for src/distortion.py.

No test framework is pinned in requirements.txt, so this is a plain script of
assert statements rather than a pytest suite — run it directly:

    .venv\\Scripts\\python.exe tests\\test_distortion.py

It exits non-zero (via AssertionError) on any failure and prints "ALL TESTS
PASSED" on success, so it is a real pass/fail check, not just a claim in a log.
"""

import sys
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from distortion import SEVERITY_FRACTIONS, distort  # noqa: E402


def _sample_image():
    """A small synthetic test image — deterministic, no dataset dependency.

    Using a synthetic image (not a real MonuMAI file) keeps this test runnable
    even before/without the dataset present, and keeps the test's own input
    fixed and version-controllable in spirit (the array is generated by fixed
    arithmetic, not randomness).
    """
    h, w = 200, 300
    image = np.zeros((h, w, 3), dtype=np.uint8)
    # A simple gradient + grid pattern so a perspective warp is visually and
    # numerically distinguishable from a no-op.
    for y in range(h):
        for x in range(w):
            image[y, x] = (x % 256, y % 256, (x + y) % 256)
    return image


def test_byte_identical_across_repeated_calls():
    """Same (image, severity, seed) must give byte-identical output every call."""
    image = _sample_image()
    for severity in SEVERITY_FRACTIONS:
        distorted_1, H_1 = distort(image, severity, seed=42)
        distorted_2, H_2 = distort(image, severity, seed=42)
        assert distorted_1.shape == distorted_2.shape
        assert distorted_1.dtype == distorted_2.dtype
        assert distorted_1.tobytes() == distorted_2.tobytes(), (
            f"severity={severity}: distorted pixels differ across repeated calls"
        )
        assert np.array_equal(H_1, H_2), f"severity={severity}: H differs across repeated calls"
    print("test_byte_identical_across_repeated_calls: PASSED")


def test_different_seeds_differ():
    """Sanity check: different seeds should (almost certainly) not collide.

    Guards against a degenerate implementation that ignores `seed` entirely
    and would otherwise pass the byte-identical test above for the wrong
    reason.
    """
    image = _sample_image()
    distorted_a, H_a = distort(image, "medium", seed=1)
    distorted_b, H_b = distort(image, "medium", seed=2)
    assert distorted_a.tobytes() != distorted_b.tobytes()
    assert not np.array_equal(H_a, H_b)
    print("test_different_seeds_differ: PASSED")


def test_output_shape_matches_input():
    """distort() must return an image the same shape as its input."""
    image = _sample_image()
    for severity in SEVERITY_FRACTIONS:
        distorted, _ = distort(image, severity, seed=7)
        assert distorted.shape == image.shape
    print("test_output_shape_matches_input: PASSED")


def test_homography_is_3x3():
    """H must be a proper 3x3 projective transform, not e.g. a 2x3 affine one."""
    image = _sample_image()
    _, H = distort(image, "severe", seed=3)
    assert H.shape == (3, 3), f"expected a 3x3 homography, got shape {H.shape}"
    print("test_homography_is_3x3: PASSED")


def test_unknown_severity_raises():
    """An invalid severity string must raise, not silently do something else."""
    image = _sample_image()
    try:
        distort(image, "extreme", seed=1)
    except ValueError:
        print("test_unknown_severity_raises: PASSED")
    else:
        raise AssertionError("expected ValueError for an unknown severity")


if __name__ == "__main__":
    test_byte_identical_across_repeated_calls()
    test_different_seeds_differ()
    test_output_shape_matches_input()
    test_homography_is_3x3()
    test_unknown_severity_raises()
    print("\nALL TESTS PASSED")
